name: build-ios-app
on:
  push:
    branches:
      - 'bb/fastlane'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MATCH_DEPLOY_KEY }}
      - uses: actions/checkout@v2
      - run: bundle install
      - run: bundle exec fastlane ios beta --verbose
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          DEVELOPER_DIR: /Applications/Xcode_15.3.app/Contents/Developer
      - uses: actions/upload-artifact@v2
        with:
          name: Addly.ipa
          path: Addly.ipa